Lab1 has been done
VadimBelyaev02/KPPLabs pull request #1
Opened 2022-02-27 14:38 UTC by VadimBelyaev02

2022-03-03 18:19 UTC, Aneanra commented on KPP1/src/main/java/com/vadim/controller/ParallelogramController.java
> +    public Double getSquare(@RequestParam(value = "width") Double width,
@VadimBelyaev02 мало возвращать Double, нужно вернуть json объект ParallelogramСharacteristic со свойствами периметр и площадь. если разделяешь на два гет-запроса, то пусть объект будет общий, но в первом случае заполняется только поле периметра, а во втором - только поле площадь. или просто сделать общее поле value, в которое при вычислении площади будет заноситься значение площади, а при вычислении периметра - значение периметра. request params пусть будут примитивного типа double.

2022-03-03 18:22 UTC, Aneanra requested changes
Вернуть Double не значит вернуть json-объект. Исправь это, пожалуйста, ещё одним коммитом.

2022-03-03 21:31 UTC, VadimBelyaev02 commented on KPP1/src/main/java/com/vadim/controller/ParallelogramController.java
> +    public Double getSquare(@RequestParam(value = "width") Double width,
Я это потом сразу во 2 лабе исправил, думал увидите) Окей, поправлю

2022-03-15 17:21 UTC, Aneanra commented on KPP1/src/main/java/com/vadim/controller/ParallelogramController.java
> +    private ParallelogramService service;
сделала это поле @Autowired

2022-03-15 17:22 UTC, Aneanra reviewed
Работа принята. Сделала поле сервиса @Autowired.

2022-03-15 17:24 UTC, merged